### ISSUE TITLE
Unable to join AG

### ISSUE THREAD

**Issue by JimiC** [enriquecatala/sqlserver-docker-alwayson#1]
I've been trying to make this work to no avail.

I'm using the following `docker compose` file:

```
version: '3'

services:
  db1:
    container_name: sqlNode1
    image: enriquecatala/sql2017_alwayson_node:latest
    hostname:
        sqlNode1
    domainname:
        enriquecatala.com
    # volumes:
    #   - mssql-server-linux-datadb1:/var/opt/mssql/data/sqlNode1
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14331:1433"
      - "15021:5022"
    networks:
      - internal

  db2:
    container_name: sqlNode2
    image: enriquecatala/sql2017_alwayson_node:latest
    hostname:
        sqlNode2
    domainname:
        enriquecatala.com
    # volumes:
    #   - mssql-server-linux-datadb2:/var/opt/mssql/data/sqlNode2
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14332:1433"
      - "15022:5022"
    networks:
      - internal

  db3:
    container_name: sqlNode3
    image: enriquecatala/sql2017_alwayson_node:latest
    hostname:
        sqlNode3
    domainname:
        enriquecatala.com
    # volumes:
    #   - mssql-server-linux-datadb3:/var/opt/mssql/data/sqlNode3
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14333:1433"
      - "15023:5022"
    networks:
      - internal

# volumes:
#   mssql-server-linux-datadb1:
#   mssql-server-linux-datadb2:  
#   mssql-server-linux-datadb3:  
  
networks:
  internal: 
```

Note here that I'm not using `volumes` because I don't want anything to persist yet during testing.

When starting the containers via: `docker-compose up -d` all nodes are starting successfully.
Inspecting the containers I can see that the certificates are in `/usr/certificate` and are owned by `root:root`. Note: There is no `mssql` user or group in the container.

I can login to the nodes via SSMS from a `Windows` machine.
Inspecting the `sql` instances I verified that the endpoints and the certificates are set.

From `sqlNode1` instance I execute the following script to create the `AG`
```
USE master
GO
CREATE AVAILABILITY GROUP [AG1]
    WITH (CLUSTER_TYPE = NONE)
    FOR REPLICA ON
    N'sqlNode1'
        WITH (
        ENDPOINT_URL = N'tcp://sqlNode1:5022',
        AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,
            SEEDING_MODE = AUTOMATIC,
            FAILOVER_MODE = MANUAL,
        SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
            ),
    N'sqlNode2'
        WITH (
        ENDPOINT_URL = N'tcp://sqlNode2:5022',
        AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,
            SEEDING_MODE = AUTOMATIC,
            FAILOVER_MODE = MANUAL,
        SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
            ),
    N'sqlNode3'
        WITH (
        ENDPOINT_URL = N'tcp://sqlNode3:5022',
        AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,
            SEEDING_MODE = AUTOMATIC,
            FAILOVER_MODE = MANUAL,
        SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
            )
```

`AG` is created successfully. `sqlNode2` and `sqlNode3` are reported as disconnected.

Now I'm login to `sqlNode2` with `sa` and when executing the following script:
```
ALTER AVAILABILITY GROUP [AG1] JOIN WITH (CLUSTER_TYPE = NONE)
```
the script times out.

The full message is:

```
Msg 47106, Level 16, State 3, Line 1
Cannot join availability group 'AG1'. Download configuration timeout. Please check primary configuration, network connectivity and firewall setup, then retry the operation.
Msg 41158, Level 16, State 3, Line 1
Failed to join local availability replica to availability group 'AG1'.  The operation encountered SQL Server error 47106 and has been rolled back.  Check the SQL Server error log for more details.  When the cause of the error has been resolved, retry the ALTER AVAILABILITY GROUP JOIN command.
```

I'm I missing something?

Any help is appreciated.

Edit: Forgot to mention that I'm trying this on an `Ubuntu 18.04` machine.
